---
- hosts: localhost
  vars:
    server_name: factorio-01
    server_type: cpx21
  roles:
    - create_server
  post_tasks:
    - meta: refresh_inventory

- hosts: factorio-01
  remote_user: root
  roles:
    - factorio_start
