---
- name: Working directory is present
  file:
    path: "{{ working_directory }}"
    state: directory

- name: SSH key is present
  command: ssh-keygen -t rsa -b 4096 -C "root@{{ server_name }}" -f {{ working_directory }}/id_rsa_{{ server_name }} -q -N ""
  args:
    creates: "{{ working_directory }}/id_rsa_{{ server_name }}"

- name: Set variables for SSH public key
  set_fact: ssh_public_key="{{ 'dummy' if ansible_check_mode else lookup('file', '{}/id_rsa_{}.pub'.format(working_directory, server_name)) }}"

- name: Create cloud server "{{ server_name }}"
  hcloud_server:
    name: "{{ server_name }}"
    location: "{{ server_location }}"
    server_type: "{{ server_type }}"
    image: "{{ server_image }}"
    state: present
    api_token: "{{ hetzner_api_key }}"
    ssh_keys: "{{ server_ssh_keys }}"
    user_data: "{{ lookup('template', 'user_data.yml.j2') }}"
  notify: wait_until_up
  register: hcloud_result

- name: Print server info
  debug:
    var: hcloud_result
