---
- name: Stop factorio service
  systemd:
    name: factorio
    state: stopped

- name: Download savegames
  fetch:
    src: /home/gameserver/factorio/saves/factorio.zip
    dest: saves/{{inventory_hostname}}.zip
    flat: yes
